// `auto_qa init` — the low-tech alternative to a Claude Code plugin. Run it once
// in a Flutter project (`dart run auto_qa init`) and it scaffolds the Claude Code
// wiring: a `.mcp.json` server registration, an `/auto-qa` skill under
// `.claude/skills/`, and (if missing) a driver-enabled `test_driver/app.dart`.
//
// The content builders below are pure (string in, string out) so they're
// unit-tested; `runInit` does the file I/O on top of them.
import 'dart:convert';
import 'dart:io';

/// Builds the `.mcp.json` contents that register the auto_qa MCP server.
///
/// [existing] is the current `.mcp.json` text (or null/empty for a fresh file);
/// any other servers and top-level keys in it are preserved. Throws
/// [FormatException] if [existing] is non-empty but not valid JSON.
String autoQaMcpJson(String? existing, {String device = 'macos'}) {
  final server = {
    'command': 'dart',
    'args': [
      'run',
      'auto_qa',
      '--launch',
      '--device=$device',
      '--target=test_driver/app.dart',
      '--artifacts=.auto_qa/shots',
    ],
  };
  final root = (existing == null || existing.trim().isEmpty)
      ? <String, dynamic>{}
      : (jsonDecode(existing) as Map).cast<String, dynamic>();
  final servers = (root['mcpServers'] as Map?)?.cast<String, dynamic>() ??
      <String, dynamic>{};
  servers['auto_qa'] = server;
  root['mcpServers'] = servers;
  return '${const JsonEncoder.withIndent('  ').convert(root)}\n';
}

/// Builds a driver-enabled `test_driver/app.dart` that wraps [packageName]'s
/// `main.dart` with the Flutter Driver extension.
String driverEntrypoint(String packageName) => '''
// Driver-enabled entrypoint generated by `auto_qa init`. For testing only — it
// lives outside lib/, so the driver extension never reaches a production build.
import 'package:flutter_driver/driver_extension.dart';
import 'package:$packageName/main.dart' as app;

void main() {
  enableFlutterDriverExtension();
  app.main();
}
''';

/// Builds the `/auto-qa` Claude Code skill that drives the app via the MCP tools.
String autoQaSkillMarkdown() => '''---
name: auto-qa
description: >-
  Drive this Flutter app hands-free for QA using the auto_qa MCP server —
  navigate screens, screenshot, type, scroll, and report bugs and visual
  issues. Use when asked to QA, smoke-test, explore, or screenshot the app.
---

# auto-qa

Drive the running Flutter app through the `auto_qa` MCP server's tools and report
what you find. The server launches the app on first use (via
`test_driver/app.dart`), so you don't need to start it yourself.

## Tools (from the `auto_qa` MCP server)

- `mcp__auto_qa__screenshot` — capture the screen. Your primary way to *see* the
  app; take one whenever the screen changes.
- `mcp__auto_qa__describe` — dump the render tree to discover widget keys/labels.
- `mcp__auto_qa__tap` — tap by `text`, `key`, or `tooltip`.
- `mcp__auto_qa__enter_text` — type into a field (optionally focus it first via
  `focus_text` / `focus_key`).
- `mcp__auto_qa__scroll` — scroll a scrollable (or the screen); negative `dy`
  scrolls down.
- `mcp__auto_qa__wait_for` — wait for a widget to be present/absent.

## Workflow

1. `screenshot` the starting screen.
2. If the screenshot is ambiguous, `describe` to find exact tappable
   labels/keys.
3. Visit each screen/section: `tap` to navigate, `wait_for` to confirm it
   rendered, `screenshot` to inspect.
4. Exercise inputs: `enter_text`, toggles, and `scroll` through long content.
5. Note both functional bugs (crashes, dead buttons, wrong data) and polish
   issues (alignment, contrast, spacing, truncation, jank).

## Reporting

Produce a concise findings list. For each issue give the screen, what's wrong,
a severity, and the screenshot path the tool saved (printed on the first line of
each `screenshot` result).

## Tips

- The app may animate continuously; the tools already handle that.
- Prefer targeting widgets by visible `text`, then `key` (ValueKey), then
  `tooltip`.
- If a tool times out, `screenshot` to re-orient before retrying.
''';

/// Scaffolds the Claude Code wiring for auto_qa into the current directory:
/// `.mcp.json`, `.claude/skills/auto-qa/SKILL.md`, and `test_driver/app.dart`.
///
/// Supported flags: `--device=NAME` (default `macos`) and `--force` (overwrite
/// the skill / driver entrypoint if they already exist).
Future<void> runInit(List<String> args) async {
  final device = _flag(args, '--device') ?? 'macos';
  final force = args.contains('--force');
  final root = Directory.current;

  _writeMcpJson(root, device: device);
  _writeSkill(root, force: force);
  _writeDriverEntrypoint(root, force: force);

  stdout.writeln('\nDone. Next:');
  stdout.writeln('  • flutter pub get');
  stdout.writeln('  • add `.auto_qa/` to your .gitignore (screenshot output)');
  stdout.writeln('  • open Claude Code in this project and run /auto-qa');
}

void _writeMcpJson(Directory root, {required String device}) {
  final f = File('${root.path}/.mcp.json');
  final existing = f.existsSync() ? f.readAsStringSync() : null;
  try {
    f.writeAsStringSync(autoQaMcpJson(existing, device: device));
    stdout.writeln(
      '${existing == null ? 'created' : 'updated'} .mcp.json (auto_qa server)',
    );
  } on FormatException catch (e) {
    stderr.writeln(
      'skipped .mcp.json — existing file is not valid JSON ($e).\n'
      'Add the auto_qa server entry manually (see the README).',
    );
  }
}

void _writeSkill(Directory root, {required bool force}) {
  final f = File('${root.path}/.claude/skills/auto-qa/SKILL.md');
  if (f.existsSync() && !force) {
    stdout.writeln(
      'skipped .claude/skills/auto-qa/SKILL.md (exists; use --force)',
    );
    return;
  }
  f.parent.createSync(recursive: true);
  f.writeAsStringSync(autoQaSkillMarkdown());
  stdout.writeln('wrote .claude/skills/auto-qa/SKILL.md (the /auto-qa skill)');
}

void _writeDriverEntrypoint(Directory root, {required bool force}) {
  final f = File('${root.path}/test_driver/app.dart');
  if (f.existsSync() && !force) {
    stdout.writeln('skipped test_driver/app.dart (exists)');
    return;
  }
  final pkg = _packageName(root);
  if (pkg == null) {
    stderr.writeln(
      'skipped test_driver/app.dart — no pubspec.yaml here. Run init from your '
      "Flutter project root, or add the entrypoint by hand (see the README).",
    );
    return;
  }
  f.parent.createSync(recursive: true);
  f.writeAsStringSync(driverEntrypoint(pkg));
  stdout.writeln('wrote test_driver/app.dart (drives package:$pkg)');
}

/// Reads the `name:` from the project's `pubspec.yaml`, or null if absent.
String? _packageName(Directory root) {
  final f = File('${root.path}/pubspec.yaml');
  if (!f.existsSync()) return null;
  final m = RegExp(
    r'^name:\s*([a-zA-Z0-9_]+)',
    multiLine: true,
  ).firstMatch(f.readAsStringSync());
  return m?.group(1);
}

String? _flag(List<String> args, String name) {
  for (final a in args) {
    if (a.startsWith('$name=')) return a.substring(name.length + 1);
  }
  return null;
}
